spring:
  application:
    name: portfolio
  profiles:
    active: dev

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.anjar.portfolio: DEBUG